apiVersion: v1
kind: Service
metadata:
  name: goserver
spec:
  selector:
    app: goserver
  ports:
    - name: goserver-server
      protocol: TCP
      port: 8000
      targetPort: 80
  type: LoadBalancer